name: Ultimate APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build using Kivy official Docker image
      run: |
        # 使用Kivy官方Docker镜像，包含所有预配置的环境
        docker run --rm \
          -v $(pwd):/src \
          -w /src \
          kivy/kivy:latest \
          bash -c "
            apt update && \
            apt install -y openjdk-11-jdk wget unzip && \
            pip install buildozer && \
            buildozer android debug
          "
          
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ultimate-apk
        path: bin/*.apk
