name: Build APK with Android Tools

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          zlib1g-dev \
          libncurses5-dev \
          wget \
          curl
        
    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv
        
    - name: Set up Android SDK (if Buildozer doesn't auto-download)
      run: |
        # 创建 Android SDK 目录
        mkdir -p ~/.android
        # 设置接受 Android 许可证
        yes | sdkmanager --licenses || true
        
    - name: Build APK with Buildozer
      run: |
        # 设置 Buildozer 自动接受 Android 许可证
        echo "Setting up Buildozer environment..."
        buildozer android clean
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
