name: Build APK with GitHub Runner

on:
  workflow_dispatch:  
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          zlib1g-dev \
          libncurses5-dev
          
    - name: Install Buildozer and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv
        
    - name: Build APK with Buildozer
      run: |
        buildozer init
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
        retention-days: 30
