name: Direct APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-11-jdk zlib1g-dev
        pip3 install buildozer
        
    - name: Build APK directly (skip clean)
      run: |
        echo "直接构建APK，跳过清理步骤..."
        buildozer -v android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-file
        path: bin/*.apk
